"""add male and female percentage field

Revision ID: 1e3f11cd783a
Revises: e35199fd6898
Create Date: 2024-08-31 14:51:09.736782

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1e3f11cd783a'
down_revision: Union[str, None] = 'e35199fd6898'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_user_email', table_name='user')
    op.drop_index('ix_user_id', table_name='user')
    op.drop_table('user')
    op.add_column('daily_reports', sa.Column('male_percentage', sa.Float(), nullable=False, server_default='0.0'))
    op.add_column('daily_reports', sa.Column('female_percentage', sa.Float(), nullable=False, server_default='0.0'))

    op.alter_column('daily_reports', 'male_percentage', server_default=None)
    op.alter_column('daily_reports', 'female_percentage', server_default=None)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('daily_reports', 'female_percentage')
    op.drop_column('daily_reports', 'male_percentage')
    op.create_table('user',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('email', sa.VARCHAR(length=320), autoincrement=False, nullable=False),
    sa.Column('hashed_password', sa.VARCHAR(length=1024), autoincrement=False, nullable=False),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('is_superuser', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('is_verified', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='user_pkey')
    )
    op.create_index('ix_user_id', 'user', ['id'], unique=False)
    op.create_index('ix_user_email', 'user', ['email'], unique=True)
    # ### end Alembic commands ###
