"""changed

Revision ID: eac51bc9ffce
Revises: 33d41fffcb7b
Create Date: 2024-07-24 00:16:12.385941

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'eac51bc9ffce'
down_revision: Union[str, None] = '33d41fffcb7b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_employees_id', table_name='employees')
    op.drop_index('ix_employees_name', table_name='employees')
    op.drop_index('ix_employees_phone_number', table_name='employees')
    op.drop_index('ix_employees_position_id', table_name='employees')
    op.drop_table('employees')
    op.drop_index('ix_employee_images_id', table_name='employee_images')
    op.drop_index('ix_employee_images_image_url', table_name='employee_images')
    op.drop_table('employee_images')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('employee_images',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('image_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('image_url', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('employee_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('device_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], name='employee_images_employee_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='employee_images_pkey'),
    sa.UniqueConstraint('employee_id', 'image_id', name='unique_image_employee')
    )
    op.create_index('ix_employee_images_image_url', 'employee_images', ['image_url'], unique=False)
    op.create_index('ix_employee_images_id', 'employee_images', ['id'], unique=False)
    op.create_table('employees',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('phone_number', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('position_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('filial_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('time_in', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('time_out', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='employees_pkey')
    )
    op.create_index('ix_employees_position_id', 'employees', ['position_id'], unique=False)
    op.create_index('ix_employees_phone_number', 'employees', ['phone_number'], unique=False)
    op.create_index('ix_employees_name', 'employees', ['name'], unique=False)
    op.create_index('ix_employees_id', 'employees', ['id'], unique=False)
    # ### end Alembic commands ###
